// @generated drizzle-zero signature:sha256:46f04ba98d50d62720ef91a5ec5f654fc43d6c2474f84e9287d3392e5866c703
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const profilesTable = {
  name: "profiles",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    username: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    avatarUrl: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "avatar_url",
    },
    isAdmin: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_admin",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    profiles: profilesTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "profiles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Profile = Row<(typeof schema)["tables"]["profiles"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;
